CREATE TABLE accounts
(
    id          INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    address     VARCHAR(255) NOT NULL,
    private_key VARCHAR(255) NOT NULL UNIQUE
);

CREATE TYPE transaction_status AS ENUM (
    'in_queue',
    'processing',
    'completed',
    'failed'
    );

-- Create the transactions table
CREATE TABLE transactions
(
    id               BIGSERIAL PRIMARY KEY,
    chain            VARCHAR(255)       NOT NULL,
    "to"             VARCHAR(255)       NOT NULL,
    data             TEXT,
    gas_limit        VARCHAR(255),
    status           transaction_status NOT NULL,
    transaction_hash VARCHAR(255),
    create_timestamp BIGINT             NOT NULL
);
